### ISSUE TITLE
愿你我都不会成为这样的人

### ISSUE THREAD

**Issue by axetroy** [axetroy/blog#176]
有些人工作了5年，却只有一年的工作经验，因为它每一年都在做同样的工作。

不思进取，安于现状，却指责那些作出改变的人。

如果你做不到马云说的 **银行不愿意改变，那我就去改变银行**

那你就少说话，多做事，多思考，让未来更美好。

愿你我都不会成为这样的人。

**Comment by MrLeeYing** [comment]
刚开始学习，想做成大神这样的blog，可以提供下技术学习路线吗？

**Comment by axetroy** [comment]
@MrLeeYing 
这个我也不知道怎么说起，面太广。
主要是有兴趣驱动

如果真的对这一行感兴趣，可以去知乎搜索相关的专业回答。
如果只是想做这么一个博客，那么照着抄，修修改改就行了。
